"""
Create a program that will play the “cows and bulls”
game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to
guess a 4-digit number. For every digit that the user
guessed correctly in the correct place, they have a
“cow”. For every digit the user guessed correctly in
the wrong place is a “bull.” Every time the user makes
a guess, tell them how many “cows” and “bulls” they
have. Once the user guesses the correct number, the
game is over. Keep track of the number of guesses the
user makes throughout teh game and tell the user at
the end.

Say the number generated by the computer is 1038.
An example interaction could look like this:

  Welcome to the Cows and Bulls Game!
  Enter a number:
   1234
  2 cows, 0 bulls
   1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
"""

import random

win = ' Wanna play again? Type a number if yes and "exit" if no: '


def cows_n_bulls(gn, rn):
    num1 = [int(n11) for n11 in str(gn)]
    num2 = [int(n22) for n22 in str(rn)]
    cows = 0
    bulls = 0

    if gn == rn:
        return win
    else:
        for n in range(4):
            if num1[n] == num2[n]:
                cows += 1
            if (num1[0] or num1[1] or num1[2] or num1[3]) == num2[n]:
                bulls += 1
        return "{} cow(s) and {} bull(s). Guess again: ".format(cows, bulls)


def generate_number(digits=4):
    res = []
    for _ in range(digits):
        res.append(str(random.randint(1, 9)))
    return int(''.join(res))


if __name__ == "__main__":
    cmd = input('''In this game you will need to guess the 4-digit number. 
    For every digit that you guessed correctly in the correct 
    place, you have a “cow”. For every digit you guessed 
    correctly in the wrong place is a “bull”. Your guess? ''')

    while cmd != 'exit':
        num = generate_number()
        i = 1
        var = True
        while var:
            cmd = int(cmd)
            if cows_n_bulls(cmd, num) == win:
                var = False
                print('Exactly right! You have tried {} times.'.format(i))
            cmd = input(cows_n_bulls(cmd, num))
            i = i + 1
